"""add_user_avatar

Revision ID: 88fa79d08a4f
Revises: f352e42232a3
Create Date: 2026-02-01 16:42:56.934296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fa79d08a4f'
down_revision: Union[str, Sequence[str], None] = 'f352e42232a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.UUID(), nullable=True, comment='头像文件ID'))
    op.create_foreign_key(op.f('fk_users_avatar_file_objects'), 'users', 'file_objects', ['avatar'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_avatar_file_objects'), 'users', type_='foreignkey')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
