"""add_rustfs_models

Revision ID: f352e42232a3
Revises: 6b7f3c8b7c12
Create Date: 2026-02-01 16:35:49.797471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f352e42232a3'
down_revision: Union[str, Sequence[str], None] = '6b7f3c8b7c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(), nullable=False, comment='业务模块'),
    sa.Column('resource', sa.String(), nullable=False, comment='资源类型'),
    sa.Column('object_key', sa.String(), nullable=False, comment='对象存储Key'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='所有者ID'),
    sa.Column('filename', sa.String(), nullable=False, comment='原始文件名'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('content_type', sa.String(), nullable=False, comment='MIME类型'),
    sa.Column('etag', sa.String(), nullable=True, comment='ETag'),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='filevisibility', native_enum=False), nullable=False, comment='可见性'),
    sa.Column('related_type', sa.String(), nullable=True, comment='关联业务类型'),
    sa.Column('related_id', sa.String(), nullable=True, comment='关联业务ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_objects')),
    sa.UniqueConstraint('object_key', name=op.f('uq_file_objects_object_key'))
    )
    op.create_index(op.f('ix_file_objects_module'), 'file_objects', ['module'], unique=False)
    op.create_index(op.f('ix_file_objects_owner_id'), 'file_objects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_file_objects_related_id'), 'file_objects', ['related_id'], unique=False)
    op.create_index(op.f('ix_file_objects_related_type'), 'file_objects', ['related_type'], unique=False)
    op.create_index(op.f('ix_file_objects_resource'), 'file_objects', ['resource'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_objects_resource'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_related_type'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_related_id'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_owner_id'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_module'), table_name='file_objects')
    op.drop_table('file_objects')
    # ### end Alembic commands ###
