"""add_knowledgebase_models

Revision ID: f6100f8abffa
Revises: 88fa79d08a4f
Create Date: 2026-02-01 20:50:12.175200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6100f8abffa'
down_revision: Union[str, Sequence[str], None] = '88fa79d08a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='kbvisibility', native_enum=False), nullable=False, comment='可见性'),
    sa.Column('embedding_model', sa.String(length=100), nullable=False, comment='Embedding模型'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='切片大小'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='切片重叠'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knowledge_bases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases'))
    )
    op.create_index(op.f('ix_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.create_table('kb_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False, comment='所属知识库ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文档标题'),
    sa.Column('file_key', sa.String(length=500), nullable=False, comment='RustFS文件路径'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型(pdf/txt/md/docx)'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', name='documentstatus', native_enum=False), nullable=False, comment='处理状态'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='切片数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_kb_documents_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_documents'))
    )
    op.create_index(op.f('ix_kb_documents_kb_id'), 'kb_documents', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_documents_status'), 'kb_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_documents_status'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_kb_id'), table_name='kb_documents')
    op.drop_table('kb_documents')
    op.drop_index(op.f('ix_knowledge_bases_user_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
